export const UNIVERSITY_BRANCH_OPTIONS = [
  "Computer Science Engineering",
  "Computer Science and Engineering (AI & ML)",
  "Computer Science and Engineering (Data Science)",
  "Computer Science and Engineering (Cyber Security)",
  "Information Technology",
  "Electronics and Communication Engineering",
  "Electronics and Electrical Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biotechnology Engineering",
  "Biomedical Engineering",
  "Instrumentation Engineering",
  "Mechatronics Engineering",
  "Robotics and Automation",
  "Automobile Engineering",
  "Aerospace Engineering",
  "Environmental Engineering",
  "Agricultural Engineering",
  "Food Technology",
  "Petroleum Engineering",
  "Mining Engineering",
  "Production Engineering",
  "Industrial Engineering",
  "Physics",
  "Chemistry",
  "Mathematics",
  "Biology",
  "Microbiology",
  "Pharmacy",
  "Commerce",
  "Economics",
  "Business Administration",
  "Management Studies",
  "Law",
  "English",
  "Hindi",
  "History",
  "Political Science",
  "Psychology",
  "Sociology",
  "Fine Arts",
  "Performing Arts",
  "Other",
] as const;